import 'package:flutter/material.dart';

const mypurple = Color.fromARGB(255, 140, 13, 179);
const myorange = Color(0xFFFE8C68);
const bgcolor = Color(0xFFF6F7FF);
const orangeGradient = Color.fromARGB(255, 255, 227, 211);
const sectext =
    'End-to-end encryption keeps your personal inforamtion and booking between you and hotel database, Not anyone can see your information even the manager.\nThis includes your:';
const secnotificationtext =
    'Get notified when your security code changes for cantact\'s phone in an end-to-end ecvrypted chat. If you have multiple devices, this setting must be enabled on each device where you want to get nontifications.';
const requestText1 =
    'create a report of your hotel account information, how many times you have logged in/out and when, times of booking rooms in hotel and how much you have paid..';
const requestText2 =
    'Your report will be ready in a few days, you have to download it when It\'s available.\n\nYour request will be canceled if you make changes to your account such as logging out while request is sent or deleting your account.';
const ourTermsText =
    'Terms and Conditions\nLast updated: March, 2024\n\nWe guarantee you the best available rate when you book a room through an official HotelName website. If you find a lower publicly available rate (“Lower Rate”) elsewhere within 24 hours of making your booking, we will match the lower rate, subject to the following terms and conditions:\n\n1. Reservations must be made through one of the HotelName official websites.\n\n2. The Lower Rate must be for the same type of accommodation, which means the same room type, at the same hotel or resort, with the same dates and length of stay, same number of guests, with a similar view or room size, same designation as either cancellable or non-cancellable, same advance purchase policies and the same terms and conditions governing the room rate.\n\n3. You must complete and submit a claim submittal web form to HotelName in accordance with the claim form\'s instructions to process the claim.\n\n4. You must submit your claim within 24 hours of the reservation being made with Four Seasons and at least 48 hours (72 hours for non-English HotelName websites) before the standard check-in time at the applicable HotelName hotel or resort.\n\n5. You may submit only one claim for each stay. A “stay” means the total number of consecutive nights spent at the same hotel or resort by the same guest or guests. You must complete the stay.\n\n6. Rate comparisons will be made net of taxes, gratuities, service charges, early departure fees, or other fees and incidental charges. Free breakfast and free or discounted amenities or services offered as part of the Lower Rate will be excluded from the rate comparison, and will not be provided by HotelName when matching the Lower Rate.\n\n7. HotelName reserves the right to deny a claim, if it cannot independently verify the availability of a Lower Rate at the time it processes the claim. The Lower Rate must be bookable on another website. Advertised or inquiry only rates do not qualify.\n\n\nIf you find a lower qualifying rate within 24 hours of making your reservation, we will match the lower rate.';
const myroomtext =
    'Thank you again for choosing [Hotel Name]. We can\'t wait to welcome you! \nAdditionally, we invite you to explore our amenities and services available during your visit. Whether it\'s dining at our restaurant, relaxing by the pool, or exploring nearby attractions, we\'re committed to making your stay with us exceptional.\nFinally, if you have any questions or need assistance with your reservation, feel free to reach out to our front desk team at 0944876334. We\'re here to ensure your stay is comfortable and enjoyable.';
